version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  app:
    image: xaimepardalc/asi-herm-deno-app:2.2.1
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
volumes:
  mongodb_data:
